# Custom Redis Config Default Memory Limit: 50MB (easy to OOM for testing)
maxmemory 50mb
maxmemory-policy noeviction
# allow 10k clients max
maxclients 10000

# turn on slowlog at 10ms
slowlog-log-slower-than 10000
slowlog-max-len 128
