#!/usr/bin/env python3
"""Generate PageZero GRPO Colab notebook with TRL 0.29+ compatibility.

Saves: /Users/dishantgarg/Documents/scaler/PageZero/pagezero_unsloth_grpo_colab_FIXED.ipynb
"""

import json
from pathlib import Path

TARGET_PATH = Path("/Users/dishantgarg/Documents/scaler/PageZero/pagezero_unsloth_grpo_colab_FIXED.ipynb")


def md_cell(lines):
    return {"cell_type": "markdown", "metadata": {}, "source": lines}


def code_cell(lines):
    return {
        "cell_type": "code",
        "metadata": {},
        "source": lines,
        "execution_count": None,
        "outputs": [],
    }

cells = [
    md_cell([
        "# PageZero GRPO Training (Colab) - Unsloth + Local or Deployed Backend",
        "",
        "This notebook trains the PageZero agent with GRPO using your existing training pipeline.",
        "",
        "You can run with any backend URL mode:",
        "- local_same_machine: use local Docker backend on the same machine as notebook",
        "- local_via_tunnel: use local Docker backend exposed by HTTPS tunnel (best for Colab)",
        "- deployed_space: use deployed backend URL (HF Space or VM URL)",
        "",
        "Only one variable controls this switch: ENV_URL (derived from BACKEND_MODE).",
    ]),

    md_cell(["## 1) Install Dependencies", "", "Includes Unsloth, TRL (>=0.29.0), vLLM, and OpenEnv runtime."]),

    code_cell([
        "import subprocess",
        "import sys",
        "from importlib import metadata",
        "",
        "subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '-U', 'pip'], check=True)",
        "",
        "core_packages = [",
        "    'transformers',",
        "    'datasets',",
        "    'accelerate',",
        "    'matplotlib',",
        "    'pandas',",
        "    'peft',",
        "    'trl>=0.29.0',",
        "    'huggingface_hub>=0.24.0,<1.0',",
        "    'openenv-core[core]>=0.2.1',",
        "]",
        "",
        "subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *core_packages], check=True)",
        "",
        "optional_packages = ['unsloth', 'vllm>=0.12.0']",
        "for pkg in optional_packages:",
        "    result = subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', pkg], check=False)",
        "    if result.returncode == 0:",
        "        print(f'Installed optional package: {pkg}')",
        "    else:",
        "        print(f'Skipping optional package on this runtime: {pkg}')",
        "",
        "for pkg in ['transformers', 'datasets', 'peft', 'trl', 'huggingface-hub']:",
        "    try:",
        "        print(f'{pkg}: {metadata.version(pkg)}')",
        "    except Exception:",
        "        print(f'{pkg}: NOT INSTALLED')",
    ]),

    code_cell(["import os", "print('Restarting kernel to apply updated TRL version...')", "os._exit(0)"]),

    md_cell(["### Runtime Restarted", "After the cell above runs, the runtime will restart automatically. Once connected again, continue with Section 2."]),

    md_cell([
        "## 2) Configuration",
        "",
        "Set token, backend mode, URLs, model, and training hyperparameters.",
        "",
        "Use this backend mode selector:",
        "- local_same_machine: local Docker backend on the same machine as notebook",
        "- local_via_tunnel: local Docker backend exposed by HTTPS tunnel (for Colab)",
        "- deployed_space: deployed backend URL (HF Space or VM endpoint)",
        "- custom_url: read URL from PAGEZERO_ENV_URL environment variable",
    ]),

    code_cell([
        "import os",
        "",
        "IN_COLAB = 'COLAB_GPU' in os.environ",
        "",
        "# --- HuggingFace token (optional unless pushing to hub) ---",
        "try:",
        "    from google.colab import userdata",
        "    if 'HF_TOKEN' not in os.environ:",
        "        token = userdata.get('HF_TOKEN')",
        "        if token:",
        "            os.environ['HF_TOKEN'] = token",
        "except Exception:",
        "    pass",
        "",
        "if 'HF_TOKEN' not in os.environ:",
        "    print('WARNING: HF_TOKEN not found. Needed only for push_to_hub.')",
        "",
        "# --- Backend mode selector ---",
        "BACKEND_MODE = 'deployed_space'  # local_same_machine | local_via_tunnel | deployed_space | custom_url",
        "",
        "LOCAL_SAME_MACHINE_URL = 'http://localhost:8000'",
        "LOCAL_TUNNEL_URL = 'https://YOUR-TUNNEL-URL.trycloudflare.com'",
        "DEPLOYED_SPACE_URL = 'https://pranayy-pagezero-agent.hf.space/'",
        "CUSTOM_ENV_URL = os.environ.get('PAGEZERO_ENV_URL', '').strip()",
        "",
        "if BACKEND_MODE == 'local_same_machine':",
        "    ENV_URL = LOCAL_SAME_MACHINE_URL",
        "elif BACKEND_MODE == 'local_via_tunnel':",
        "    ENV_URL = LOCAL_TUNNEL_URL",
        "elif BACKEND_MODE == 'deployed_space':",
        "    ENV_URL = DEPLOYED_SPACE_URL",
        "elif BACKEND_MODE == 'custom_url':",
        "    if not CUSTOM_ENV_URL:",
        "        raise ValueError(\"BACKEND_MODE='custom_url' but PAGEZERO_ENV_URL is empty.\")",
        "    ENV_URL = CUSTOM_ENV_URL",
        "else:",
        "    raise ValueError(f'Unknown BACKEND_MODE: {BACKEND_MODE}')",
        "",
        "if IN_COLAB and BACKEND_MODE == 'local_same_machine':",
        "    print('WARNING: localhost points to the Colab VM, not your laptop.')",
        "    print('Use local_via_tunnel or deployed_space for Colab.')",
        "",
        "# --- Repo / checkout config ---",
        "REPO_URL = 'https://github.com/Dishant-garg/PageZero-RL.git'",
        "USE_EXISTING_CHECKOUT = not IN_COLAB",
        "EXISTING_CHECKOUT_DIR = os.getcwd() if not IN_COLAB else '/content/PageZero'",
        "CLONE_DIR = '/content/PageZero' if IN_COLAB else EXISTING_CHECKOUT_DIR",
        "",
        "# --- Model config ---",
        "USE_UNSLOTH_MODEL = False  # True will try 4-bit Unsloth model id",
        "UNSLOTH_MODEL_ID = 'unsloth/Qwen3-0.6B-bnb-4bit'",
        "BASE_MODEL_ID = 'Qwen/Qwen3-0.6B'",
        "MODEL_ID = UNSLOTH_MODEL_ID if USE_UNSLOTH_MODEL else BASE_MODEL_ID",
        "FALLBACK_MODEL_ID = BASE_MODEL_ID",
        "",
        "# --- Training hyperparameters ---",
        "NUM_EPISODES = 50",
        "NUM_GENERATIONS = 8",
        "MAX_TURNS = 15",
        "MAX_NEW_TOKENS = 512",
        "VLLM_MODE = 'colocate'",
        "OUTPUT_DIR_BASE = 'outputs/pagezero-colab'",
        "",
        "# --- Hub push config ---",
        "PUSH_TO_HUB = False",
        "HUB_REPO = 'pranayy/pagezero_agent'",
        "",
        "print(f'IN_COLAB      : {IN_COLAB}')",
        "print(f'BACKEND_MODE  : {BACKEND_MODE}')",
        "print(f'ENV_URL       : {ENV_URL}')",
        "print(f'MODEL_ID      : {MODEL_ID}')",
        "print(f'EPISODES      : {NUM_EPISODES}')",
        "print(f'GENERATIONS   : {NUM_GENERATIONS}')",
    ]),

    md_cell(["## 3) Project Setup", "", "If running in Colab, clone your repository first.\nIf running from an existing local checkout, keep USE_EXISTING_CHECKOUT = True."]),

    code_cell([
        "import os",
        "import subprocess",
        "",
        "if USE_EXISTING_CHECKOUT:",
        "    CLONE_DIR = EXISTING_CHECKOUT_DIR",
        "    if not os.path.exists(CLONE_DIR):",
        "        raise FileNotFoundError(f'Existing checkout not found: {CLONE_DIR}')",
        "else:",
        "    if 'YOUR_ORG' in REPO_URL:",
        "        raise ValueError('Please set REPO_URL to your real project repository URL first.')",
        "    if not os.path.exists(CLONE_DIR):",
        "        subprocess.run(['git', 'clone', REPO_URL, CLONE_DIR], check=True)",
        "",
        "os.chdir(CLONE_DIR)",
        "subprocess.run(['pip', 'install', '-q', '-e', '.[train]'], check=True)",
        "",
        "print(f'Working directory: {os.getcwd()}')",
    ]),

    md_cell(["## 4) Smoke Test - Verify Backend Connectivity", "", "Connect to the selected backend URL, run reset, and execute one safe action."]),

    code_cell(["pwd()"]),
    code_cell(["ls"]),

    code_cell([
        "import requests",
        "import os",
        "import sys",
        "",
        "if os.path.abspath('..') not in sys.path:",
        "    sys.path.append(os.path.abspath('..'))",
        "",
        "from PageZero.client import PageZeroEnvClient",
        "from PageZero.models import PageZeroAction",
        "",
        "print(f'Testing backend: {ENV_URL}')",
        "",
        "for suffix in ['/health']:",
        "    url = ENV_URL.rstrip('/') + suffix",
        "    try:",
        "        r = requests.get(url, timeout=10)",
        "        print(f'{url} -> {r.status_code}')",
        "    except Exception as e:",
        "        print(f'{url} -> request failed: {e}')",
        "",
        "env = PageZeroEnvClient(base_url=ENV_URL)",
        "try:",
        "    reset_result = env.reset()",
        "    obs = reset_result.observation",
        "    print('Reset successful')",
        "    print(f'Step {obs.step}/{obs.max_steps}')",
        "    print(f'Active alerts: {obs.active_alerts}')",
        "",
        "    step_result = env.step(PageZeroAction(tool='check_alerts', args={}))",
        "    step_obs = step_result.observation",
        "    print(f'Step reward: {step_result.reward}')",
        "    print(f'Done: {step_result.done}')",
        "    print(f'SLA status: {step_obs.sla_status}')",
        "finally:",
        "    env.close()",
    ]),

    md_cell(["## 5) Import Training Utilities"]),

    code_cell([
        "import csv",
        "import logging",
        "import os",
        "import subprocess",
        "import sys",
        "from datetime import datetime",
        "from pathlib import Path",
        "from importlib import metadata",
        "",
        "required_specs = {",
        "    'datasets': 'datasets',",
        "    'transformers': 'transformers',",
        "    'trl': 'trl>=0.29.0',",
        "}",
        "",
        "missing_specs = []",
        "for dist_name, pip_spec in required_specs.items():",
        "    try:",
        "        metadata.version(dist_name)",
        "    except metadata.PackageNotFoundError:",
        "        missing_specs.append(pip_spec)",
        "",
        "try:",
        "    hub_version = metadata.version('huggingface-hub')",
        "except metadata.PackageNotFoundError:",
        "    hub_version = None",
        "",
        "needs_hub_fix = hub_version is None or int(hub_version.split('.')[0]) >= 1",
        "",
        "if needs_hub_fix or missing_specs:",
        "    install_specs = []",
        "    if needs_hub_fix:",
        "        install_specs.append('huggingface_hub>=0.24.0,<1.0')",
        "    install_specs.extend(missing_specs)",
        "    print('Installing/adjusting:', ', '.join(install_specs))",
        "    subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', *install_specs], check=True)",
        "",
        "print(f\"huggingface-hub version: {metadata.version('huggingface-hub')}\")",
        "",
        "for mod_name in list(sys.modules):",
        "    if mod_name.startswith(('transformers', 'peft', 'accelerate', 'trl')):",
        "        sys.modules.pop(mod_name, None)",
        "",
        "from datasets import Dataset",
        "from transformers import AutoTokenizer",
        "from trl import GRPOConfig, GRPOTrainer",
        "from peft import LoraConfig",
        "",
        "if os.path.abspath('..') not in sys.path:",
        "    sys.path.append(os.path.abspath('..'))",
        "",
        "from PageZero.train import (",
        "    SYSTEM_PROMPT,",
        "    PageZeroToolEnv,",
        "    plot_rewards,",
        "    patch_trl_vllm_compat,",
        ")",
        "",
        "patch_trl_vllm_compat()",
        "",
        "logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')",
        "logger = logging.getLogger(__name__)",
        "",
        "print('Imported training utilities successfully.')",
        "print('System prompt preview:')",
        "print(SYSTEM_PROMPT[:220] + '...')",
    ]),

    md_cell(["## 6) Build GRPO Trainer"]),

    code_cell([
        "tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)",
        "if tokenizer.pad_token is None:",
        "    tokenizer.pad_token = tokenizer.eos_token",
        "",
        "PageZeroToolEnv.BASE_URL = ENV_URL",
        "",
        "prompt_messages = [",
        "    {'role': 'system', 'content': SYSTEM_PROMPT},",
        "    {'role': 'user', 'content': 'Diagnose and fix this production incident.'},",
        "]",
        "dataset = Dataset.from_dict({'prompt': [prompt_messages for _ in range(NUM_EPISODES)]})",
        "",
        "timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')",
        "output_dir = Path(f'{OUTPUT_DIR_BASE}-{timestamp}')",
        "output_dir.mkdir(parents=True, exist_ok=True)",
        "",
        "reward_log_path = output_dir / 'reward_log.csv'",
        "with open(reward_log_path, 'w', newline='') as f:",
        "    csv.writer(f).writerow(['episode', 'total_reward', 'diagnosis_reward', 'fix_reward', 'timestamp'])",
        "",
        "def log_episode(total_r, diag_r, fix_r):",
        "    # simple CSV logger for episodes",
        "    with open(reward_log_path, 'a', newline='') as f:",
        "        csv.writer(f).writerow([total_r, diag_r, fix_r, datetime.now().isoformat()])",
        "",
        "def reward_total(completions=None, environments=None, **kwargs):",
        "    if not environments:",
        "        count = len(completions) if completions is not None else 0",
        "        return [0.0 for _ in range(count)]",
        "    values = []",
        "    for env in environments:",
        "        total = float(getattr(env, 'total_reward', 0.0))",
        "        diag = float(getattr(env, 'diagnosis_reward', 0.0))",
        "        fix = float(getattr(env, 'fix_reward', 0.0))",
        "        values.append(total)",
        "        if not getattr(env, '_episode_logged', False):",
        "            log_episode(total, diag, fix)",
        "            env._episode_logged = True",
        "    return values",
        "",
        "def reward_diagnosis(completions=None, environments=None, **kwargs):",
        "    if not environments:",
        "        count = len(completions) if completions is not None else 0",
        "        return [0.0 for _ in range(count)]",
        "    return [float(getattr(env, 'diagnosis_reward', 0.0)) for env in environments]",
        "",
        "def reward_fix(completions=None, environments=None, **kwargs):",
        "    if not environments:",
        "        count = len(completions) if completions is not None else 0",
        "        return [0.0 for _ in range(count)]",
        "    return [float(getattr(env, 'fix_reward', 0.0)) for env in environments]",
        "",
        "grpo_config = GRPOConfig(",
        "    use_vllm=True,",
        "    vllm_mode=VLLM_MODE,",
        "    output_dir=str(output_dir),",
        "    num_train_epochs=1,",
        "    learning_rate=2e-6,",
        "    lr_scheduler_type='cosine',",
        "    warmup_steps=2,",
        "    max_grad_norm=1.0,",
        "    gradient_accumulation_steps=8,",
        "    per_device_train_batch_size=1,",
        "    generation_batch_size=NUM_GENERATIONS,",
        "    num_generations=NUM_GENERATIONS,",
        "    max_completion_length=MAX_NEW_TOKENS,",
        "    max_tool_calling_iterations=MAX_TURNS,",
        "    logging_steps=1,",
        "    save_strategy='steps',",
        "    save_steps=10,",
        "    temperature=1.0,",
        "    report_to='none',",
        "    gradient_checkpointing=True,",
        "    gradient_checkpointing_kwargs={'use_reentrant': False},",
        "    save_total_limit=3,",
        "    loss_type='dapo',",
        "    mask_truncated_completions=True,",
        "    beta=0.01,",
        ")",
        "",
        "peft_config = LoraConfig(",
        "    r=16,",
        "    lora_alpha=32,",
        "    lora_dropout=0.05,",
        "    bias='none',",
        "    task_type='CAUSAL_LM',",
        "    target_modules=['q_proj', 'k_proj', 'v_proj', 'o_proj'],",
        ")",
        "",
        "trainer = GRPOTrainer(",
        "    model=MODEL_ID,",
        "    processing_class=tokenizer,",
        "    reward_funcs=[reward_total, reward_diagnosis, reward_fix],",
        "    train_dataset=dataset,",
        "    args=grpo_config,",
        "    peft_config=peft_config,",
        "    environment_factory=PageZeroToolEnv,",
        ")",
        "",
        "print(f'Trainer initialized. Output path: {output_dir}')",
    ]),

    md_cell(["## 7) Train, Plot Rewards, and Optional Hub Push"]),

    code_cell([
        "import pandas as pd",
        "from IPython.display import display, Image",
        "",
        "print('Starting GRPO training...')",
        "print(f'  Model       : {MODEL_ID}')",
        "print(f'  Episodes    : {NUM_EPISODES}')",
        "print(f'  Generations : {NUM_GENERATIONS}')",
        "print(f'  Environment : {ENV_URL}')",
        "print()",
        "",
        "try:",
        "    trainer.train()",
        "finally:",
        "    PageZeroToolEnv.close_all()",
        "    try:",
        "        plot_rewards(reward_log_path, output_dir / 'reward_plot.png')",
        "    except Exception as e:",
        "        print(f'WARNING: could not generate reward plot: {e}')",
        "",
        "trainer.save_model(str(output_dir))",
        "print(f'Model saved to {output_dir}')",
        "",
        "if reward_log_path.exists():",
        "    df = pd.read_csv(reward_log_path)",
        "    display(df.tail(10))",
        "",
        "reward_png = output_dir / 'reward_plot.png'",
        "if reward_png.exists():",
        "    display(Image(filename=str(reward_png)))",
        "",
        "if PUSH_TO_HUB:",
        "    if 'HF_TOKEN' not in os.environ:",
        "        raise RuntimeError('HF_TOKEN not set. Add it in Colab secrets or env vars.')",
        "    trainer.push_to_hub(repo_id=HUB_REPO)",
        "    print(f'Model pushed to https://huggingface.co/{HUB_REPO}')",
        "else:",
        "    print('Skipping push. Set PUSH_TO_HUB=True to enable.')",
    ]),
]

notebook = {
    "cells": cells,
    "metadata": {
        "colab": {"provenance": []},
        "kernelspec": {"display_name": "Python 3", "name": "python3"},
        "language_info": {"name": "python"},
    },
    "nbformat": 4,
    "nbformat_minor": 4,
}

TARGET_PATH.parent.mkdir(parents=True, exist_ok=True)
with TARGET_PATH.open("w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print(f"✅ Fixed notebook created: {TARGET_PATH}")
print(f"   Exists: {TARGET_PATH.exists()}")
print(f"   Size: {TARGET_PATH.stat().st_size:,} bytes")
